name: Run Tests on Merge to develop or main

on:
  push:
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-apis:
    runs-on: ubuntu-latest
    env: 
      AZURE_CU_CONFIG_Endpoint: ${{ secrets.AZURE_CU_CONFIG_Endpoint }}
      AZURE_CU_CONFIG_ApiVersion: ${{ secrets.AZURE_CU_CONFIG_ApiVersion }}
      TRAINING_DATA_SAS_URL: ${{ secrets.TRAINING_DATA_SAS_URL }}
      REFERENCE_DOCS_SAS_URL: ${{ secrets.REFERENCE_DOCS_SAS_URL }}
      
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal